#!/usr/bin/env python3
"""
Runner for graph.json — TV Graphics Production workflow.

Registers stub handlers so the graph can be executed locally
without real external services. Replace stubs with real
implementations when integrating with production systems.
"""

import json
import sys
from langgraph.types import Command
from comp import GraphSpecCompiler, LocalRegistry, load_spec


# ── LLM runner (stub) ──────────────────────────────────────────

def stub_llm_runner(config, inputs):
    """Simulates LLM response based on node config."""
    system_prompt = config.get("system_prompt", "")

    # AI brief node
    if "AI-бриф" in system_prompt or "route_suggestion" in json.dumps(config.get("output_schema", {})):
        return {
            "normalized_request": inputs.get("request", {"stub": True}),
            "missing_fields": [],
            "route_suggestion": "collage",
            "urgency_suggestion": "normal",
            "deadline_hint": "2 hours",
            "confidence": 0.92,
        }

    # RT draft node
    if "RT draft" in system_prompt:
        return {
            "template": "news_lower_third",
            "payload": {"text": "Stub RT payload", "style": "default"},
            "preview_notes": ["Generated by stub"],
        }

    # Collage draft node
    if "Collage draft" in system_prompt:
        return {
            "variants": [{"id": "v1", "layout": "default"}],
            "asset_pack": {"format": "psd", "resolution": "1920x1080"},
            "preview_notes": ["Generated by stub"],
        }

    # Motion draft node
    if "Motion draft" in system_prompt:
        return {
            "styleframes": [{"id": "sf1", "description": "Opening frame"}],
            "animatic_outline": {"duration_sec": 10, "fps": 25},
            "preview_notes": ["Generated by stub"],
        }

    # Fallback: generate from schema
    schema = config.get("output_schema", {})
    props = schema.get("properties", {})
    result = {}
    for key, prop in props.items():
        t = prop.get("type", "string")
        if t == "object":
            result[key] = {"stub": True}
        elif t == "array":
            result[key] = []
        elif t == "number":
            result[key] = 0.92
        elif t == "integer":
            result[key] = 0
        else:
            result[key] = f"stub_{key}"
    return result or {"stub": True}


# ── Retrieval runner (stub) ───────────────────────────────────

def stub_retrieval_runner(config, inputs):
    """Simulates design context retrieval."""
    return {
        "documents": [
            {
                "source": config.get("source", "design_guidelines"),
                "score": 0.9,
                "text": "Stub design guideline: use brand colors, 1920x1080, safe zone margins.",
            }
        ]
    }


# ── Function handlers ──────────────────────────────────────────

def brief_validate(inputs):
    """Validates brief completeness."""
    brief = inputs.get("brief", {}) or {}
    missing = brief.get("missing_fields", []) if brief else []
    if missing:
        return {"status": "missing_data", "missing": missing}
    return {"status": "complete", "missing": []}


def brief_merge_clarification(inputs):
    """Merges clarification data back into the request."""
    request = inputs.get("request", {}) or {}
    brief = inputs.get("brief", {}) or {}
    clarification = inputs.get("clarification", {}) or {}
    merged = {**request}
    if isinstance(clarification, dict):
        merged.update(clarification)
    return merged


def routing_confirm_priority(inputs):
    """Confirms routing and priority; detects conflicts."""
    brief = inputs.get("brief", {}) or {}
    route = brief.get("route_suggestion", "collage")
    urgency = brief.get("urgency_suggestion", "normal")
    return {
        "route": route,
        "urgency": urgency,
        "priority_conflict": False,
    }


def routing_apply_resolution(inputs):
    """Applies priority conflict resolution."""
    classification = inputs.get("classification", {}) or {}
    approval = inputs.get("approval", {}) or {}
    updated = {**classification}
    if approval.get("priority"):
        updated["urgency"] = approval["priority"]
    return updated


def review_capture_outcome(inputs):
    """Captures editorial review outcome."""
    approval = inputs.get("approval", {}) or {}
    iteration_count = inputs.get("iteration_count") or 0
    return {
        "approval_status": approval.get("status", "approved"),
        "review_comments": approval.get("comments", []),
        "iteration_count": iteration_count + 1,
    }


# ── Tool runners ───────────────────────────────────────────────

def stub_tool(tool_spec, inputs):
    """Generic stub for all unresolved tools."""
    tool_id = tool_spec.get("id", "unknown")
    return {"ok": True, "tool": tool_id, "echo": inputs, "id": "stub_001"}


# ── Build registry ─────────────────────────────────────────────

def make_registry():
    registry = LocalRegistry()

    # LLM runner
    registry.register_llm_runner("stub_llm", stub_llm_runner)

    # Retrieval runner
    registry.register_retrieval("stub_retrieval", stub_retrieval_runner)

    # Function handlers
    registry.register_function("brief.validate", brief_validate)
    registry.register_function("brief.merge_clarification", brief_merge_clarification)
    registry.register_function("routing.confirm_priority", routing_confirm_priority)
    registry.register_function("routing.apply_resolution", routing_apply_resolution)
    registry.register_function("review.capture_outcome", review_capture_outcome)

    # Tool runners (all unresolved tools use the same stub)
    for tool_id in [
        "workflow.create_request",
        "workflow.send_clarification",
        "vizrt.publish_draft",
        "drop.publish_collage_draft",
        "drop.publish_motion_draft",
        "cosmedia.deploy_rt",
        "drop.publish_final_collage",
        "drop.publish_final_motion",
        "nle.send_links",
        "workflow.close_request",
    ]:
        registry.register_tool(tool_id, stub_tool)

    return registry


# ── Auto-approve interrupts ────────────────────────────────────

AUTO_APPROVALS = {
    "await_clarification": {"source": "clarified", "extra_data": "stub clarification"},
    "resolve_priority_conflict": {"status": "approved", "priority": "confirmed"},
    "rt_finalize": {"status": "approved", "comments": []},
    "rt_editorial_review": {"status": "approved", "comments": []},
    "collage_finalize": {"status": "approved", "comments": []},
    "collage_editorial_review": {"status": "approved", "comments": []},
    "motion_finalize": {"status": "approved", "comments": []},
    "motion_editorial_review": {"status": "approved", "comments": []},
    "rt_rework": {"status": "approved", "asset": {"reworked": True}},
    "collage_rework": {"status": "approved", "asset": {"reworked": True}},
    "motion_rework": {"status": "approved", "asset": {"reworked": True}},
}


# ── Main ───────────────────────────────────────────────────────

def main():
    spec_path = sys.argv[1] if len(sys.argv) > 1 else "graph.json"
    input_text = sys.argv[2] if len(sys.argv) > 2 else "Сделать плашку для новостного выпуска"

    spec = load_spec(spec_path)
    registry = make_registry()
    compiler = GraphSpecCompiler(
        registry,
        default_llm_runner="stub_llm",
        default_retrieval_runner="stub_retrieval",
    )
    graph = compiler.compile_spec(spec)

    payload = {"input": {"text": input_text}}
    config = {"configurable": {"thread_id": "local-1"}}

    print(f"Running graph: {spec['graph_id']}")
    print(f"Input: {input_text}\n")

    # First invocation
    result = graph.invoke(payload, config=config)

    # Handle interrupts (approval nodes) automatically
    max_iterations = 20
    iteration = 0
    while iteration < max_iterations:
        state = graph.get_state(config)
        if not state.tasks or not any(t.interrupts for t in state.tasks):
            break

        for task in state.tasks:
            if task.interrupts:
                node_id = task.name
                interrupt_data = task.interrupts[0].value
                print(f"[Auto-approve] Node: {node_id}")
                print(f"  Message: {interrupt_data.get('message', 'N/A')}")

                approval = AUTO_APPROVALS.get(node_id, {"status": "approved"})
                result = graph.invoke(
                    Command(resume=approval),
                    config=config,
                )
        iteration += 1

    print("\n── Result ──")
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
